### ISSUE TITLE
How to Encrypt 

### ISSUE THREAD

**Issue by harsh288** [fluent/fluent-plugin-sql#121] opened 2022-02-01 16:24 UTC
@cosmo0920 Could you please mention comments before closing the below issue, I'm looking for a solution desperately, I don't think it's difficult for moderators to solve this issue.

Not solved issue link:
[https://github.com/fluent/fluent-plugin-sql/issues/106](url)

**Comment by ashie** [comment] 2022-02-02 01:17
Duplicate of #106

**Closed by ashie** 2022-02-02 01:17 UTC
