### ISSUE TITLE
How to encrypt password ?

### ISSUE THREAD

**Issue by harsh288** [fluent/fluent-plugin-sql#120] opened 2022-01-29 06:56 UTC
Hi @ashie 

I'm not sure how to reopen an existing issue, please check my comments on the forum, this is really an hot issue over here and I need your urgent attention with the possible solution

https://github.com/fluent/fluent-plugin-sql/issues/106

**Comment by cosmo0920** [comment] 2022-02-01 08:25
Duplicate of #106

**Closed by cosmo0920** 2022-02-01 08:25 UTC
